### ISSUE TITLE
小白麻烦请教一下。。。

### ISSUE THREAD

**Issue by Jioji1321** [lewis007/spring-boot-jpa-h2#1]
作者你好，我下载了你的项目，运行的时候提示报错。报错信息如截图所示。据我所知，System.out.println()应该没有println(String,String)的方法。想问一下你原来编辑代码的时候可以正常运行吗？麻烦解答一下，谢谢。：）
![报错信息](https://user-images.githubusercontent.com/26221676/62929537-45f39180-bded-11e9-9603-9990ecdf8a78.png)

**Comment by lewis2951** [comment]
现在重构了部分工程，项目比较忙，大部分工程做了一半，还有点问题，没法提交。忙过这阵子就更新下。
